/* eslint-disable @next/next/no-html-link-for-pages */
import { ConsultationLink } from "@/components/ConsultationLink";
import { ProcessTimeline } from "@/components/sections/ProcessTimeline";
import { ConsultationCTA } from "@/components/sections/ConsultationCTA";
import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("About NeuraX | Practical Digital Solutions UK", "NeuraX helps UK businesses build professional websites, useful web applications and practical automation around real business goals.", "/about");

const values = [["Business first", "We understand the problem before recommending technology."], ["Clear communication", "We explain decisions plainly and keep scope visible."], ["Built around you", "The solution follows your requirements, users and budget."], ["Ready for what comes next", "Maintainability and future growth are considered from the start."], ["Transparent pricing", "Starting guides and agreed quotations reduce surprises."], ["Support after launch", "Ongoing assistance is available when the project needs it."]];

export default function AboutPage() {
  return <main><section className="page-hero"><Container className="page-hero-grid"><div><p className="breadcrumb"><a href="/">Home</a><span>/</span><span>About</span></p><p className="eyebrow eyebrow-light"><span />ABOUT NEURAX</p><h1>Technology should make business easier — <em>not more complicated.</em></h1><p>A practical UK digital solutions partner for businesses that want a stronger online presence, useful software and less repetitive work.</p></div><div className="page-hero-aside"><strong>Problem first. Technology second.</strong><p>We do not force businesses into a specific platform. We find the right route for the goal, requirements and budget.</p></div></Container></section><section className="content-section"><Container className="content-grid"><div><h2>A clear route from business challenge to digital solution.</h2><p>NeuraX designs and develops professional websites, custom web applications and intelligent automation systems for businesses that want to strengthen their digital presence and reduce unnecessary manual work.</p><p>We start by understanding the problem. Then we recommend and build a solution around your goals, requirements and budget.</p><ConsultationLink className="button button-primary">Let&apos;s Discuss Your Idea</ConsultationLink></div><div className="outcome-panel"><span>OUR POSITION</span><h3>Build smarter. Automate more. Grow faster.</h3><p>Whether you are launching your first website, improving an existing system or exploring AI automation, NeuraX can help turn the idea into a practical digital solution.</p></div></Container></section><section className="section section-alt"><Container><SectionHeading eyebrow="WHY WORK WITH NEURAX?" title={<>Professional thinking. <em>Practical delivery.</em></>} /><div className="reasons-grid">{values.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></Container></section><section className="section"><Container><SectionHeading eyebrow="FROM IDEA TO LAUNCH" title={<>A process designed to keep <em>decisions clear.</em></>} /><ProcessTimeline /></Container></section><ConsultationCTA /></main>;
}
