import { LegalNav } from "@/components/layout/LegalNav";
import { Container } from "@/components/ui/Container";
import { siteConfig } from "@/lib/config";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Privacy Policy | NeuraX", "How NeuraX collects, uses and protects personal information submitted through this website.", "/privacy-policy");

export default function PrivacyPage() {
  return <main><Container className="legal-layout"><LegalNav /><article className="legal-content"><h1>Privacy Policy</h1><p>Last reviewed: 4 September 2026</p><p>This page explains how NeuraX handles personal information submitted through this website. Before publication, the business owner should review this policy and complete every highlighted item.</p><section><h2>1. Business and data controller</h2><p>Business/legal name: <span className="owner-confirm">[BUSINESS OWNER TO CONFIRM]</span></p><p>Business address: <span className="owner-confirm">[BUSINESS OWNER TO CONFIRM]</span></p><p>Contact email: <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></p></section><section><h2>2. Information we may collect</h2><p>We may collect your name, business name, email address, phone number, project requirements, budget range, preferred consultation time and any information you choose to include in a message.</p></section><section><h2>3. Why we use this information</h2><ul><li>To respond to enquiries and consultation requests.</li><li>To understand potential project requirements and prepare proposals.</li><li>To provide agreed services and support.</li><li>To protect the website from misuse and maintain basic records.</li></ul></section><section><h2>4. Lawful basis</h2><p>Depending on the interaction, information may be processed to take steps at your request before entering a contract, to perform a contract, with consent, or for legitimate business interests such as responding to genuine enquiries.</p></section><section><h2>5. Service providers and international transfers</h2><p>Website hosting, form delivery, email, analytics or other service providers may process limited data on our behalf. The final provider list and any international transfer safeguards must be confirmed: <span className="owner-confirm">[BUSINESS OWNER TO CONFIRM]</span>.</p></section><section><h2>6. Retention</h2><p>Personal information is kept only for as long as needed for the purpose it was collected, legal obligations and reasonable business records. Specific retention periods: <span className="owner-confirm">[BUSINESS OWNER TO CONFIRM]</span>.</p></section><section><h2>7. Your rights</h2><p>Depending on applicable UK data protection law, you may have rights to access, correct, erase, restrict or object to processing, and to data portability. You may also complain to the Information Commissioner&apos;s Office.</p></section><section><h2>8. Contact</h2><p>For privacy questions or requests, email <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>.</p></section></article></Container></main>;
}
