import { LegalNav } from "@/components/layout/LegalNav";
import { Container } from "@/components/ui/Container";
import { siteConfig } from "@/lib/config";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Terms & Conditions | NeuraX", "Website use and service information for NeuraX digital solutions.", "/terms");

export default function TermsPage() {
  return <main><Container className="legal-layout"><LegalNav /><article className="legal-content"><h1>Terms &amp; Conditions</h1><p>Last reviewed: 4 September 2026</p><p>These terms provide a website-level structure and must be reviewed for the owner&apos;s final legal and commercial requirements before publication.</p><section><h2>1. Business information</h2><p>Legal/business name, trading status, registration number and address: <span className="owner-confirm">[BUSINESS OWNER TO CONFIRM]</span></p><p>Email: <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></p></section><section><h2>2. Website information</h2><p>Information on this site is general and may change. We aim to keep it accurate, but project suitability, technical feasibility, availability, timescales and final pricing are confirmed only in an agreed written proposal or contract.</p></section><section><h2>3. Starting prices</h2><p>All displayed prices are starting guides, not guaranteed fixed quotations. Final pricing depends on project scope, content, functionality, integrations and technical requirements. Third-party subscriptions, domains, hosting and paid services are discussed separately where applicable.</p></section><section><h2>4. Free consultation</h2><p>The initial 30-minute consultation is offered without obligation. It provides general project discussion and does not create a contract or guarantee that a project can be accepted.</p></section><section><h2>5. Project agreements</h2><p>Specific deliverables, fees, payment dates, responsibilities, intellectual property, support and cancellation terms will be documented for each accepted project: <span className="owner-confirm">[BUSINESS OWNER TO CONFIRM FINAL CONTRACT PROCESS]</span>.</p></section><section><h2>6. External websites</h2><p>Links to external websites are provided for convenience. NeuraX is not responsible for external content, availability or privacy practices.</p></section><section><h2>7. Liability and governing law</h2><p>Appropriate liability limits, governing law and jurisdiction must be reviewed and confirmed for the business: <span className="owner-confirm">[BUSINESS OWNER TO CONFIRM]</span>.</p></section></article></Container></main>;
}
